# site settings
title: Nicolas G. Morales
subtitle: Portfolio
email: nicolasgmorales@u.northwestern.edu
description: Hi! My name is Nick, welcome to my portfolio.
baseurl: "/ngm" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1200 Simpson St Apt 2E
city: Evanston
state: IL
zip_code: 60210
country: United States of America
phone: (937) 776-0843

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ngmor
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/nicolasgmorales/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
