# site settings
title: Nicolas G. Morales
subtitle: Portfolio
email: nicolasgmorales@u.northwestern.edu
description: Hi! My name is Nick, welcome to my portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ngmor.github.io" # the base hostname & protocol for your site
author:
street_address: 1200 Simpson St Apt 2E
city: Evanston
state: IL
zip_code: 60210
country: United States of America
phone: (937) 776-0843
contact_form_id: xeqdvdwn

# homepage tiles
tiles-source: projects # accepts "posts" or "pages" or "projects"
tiles-count: 10

collections:
  projects:
    output: true
    permalink: /:collection/:path/

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: https://www.linkedin.com/in/nicolasgmorales/
  GitHub: https://github.com/ngmor
  GitLab:
  Google-Plus:
  Instagram:
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
